### ISSUE TITLE
PSU : La règle d'arrondis n'est pas la bonne (troncature demandée par la CAF)

### ISSUE THREAD

**Issue by mistraloz** [studio1247/gertrude#18]
Bonjour Bertrand,

## La règle de troncature

Selon certaines CAF, la règle de calcul du montant horaire doit correspondre à une troncature et non à un arrondi (assiette_mensuelle * taux_effort). Par ailleurs, la directrice d'une des crèches du réseau m'a affirmé que le montant horaire pour une famille à hauts revenus sans autres enfants à charge (taux d'effort à 0.06) est plafoné à 2.90. Hors le plafond de l'assiette annuelle pour la CNAF en 2015 est de 58146.21€.

`(58146.51/12)*0.06/100 = 2,907...`

J'ai donc repris les circulaires de la CNAF... mais aucune information au sujet de cette troncature. Je n'ai pas non plus confirmer les dires de la directrice sur ce montant maximum. 

Cependant, je suis allé sur le site de mon-enfant.fr (site maintenu par la CNAF), et il y a [un simulateur] (http://www.mon-enfant.fr/web/guest/tarification-garde-enfant)

En renseignant des revenus aux plafonds, qui correspondent bien (selon mon calcul) à 2,907, mon-enfant.fr affiche un montant horaire à 2.90€ (tout rond !). A défaut de base légale, cela semble au moins la pratique admise par la CNAF. De plus, c'est cohérent avec ce qui est dit par certaines CAF lors des contrôles. 

Soit cette base légale est disponible ailleurs, soit c'est symplement une règle tacite. Quoiqu'il en soit, il semble que la règle générale est bien la troncature. 

## Solution à appliquer

Fort de cette analyse, il semble que ligne 398 du fichier cotisation.py, il y a `round(self.montant_heure_garde, 2)` alors qu'il devrait y avoir `math.floor(self.montant_heure_garde*100)/100`. 

J'ai plusieurs options : 
1. Corriger directement. Cependant la modification n'est pas rétrocompatible
2. Placer une option de configuration. Cependant comme ce n'est pas au libre choix de la crèche (mais une directive de la CNAF), le ne choix ne se justifie pas
3. Ne pas répercuter la modification sur le dépot principale (je peux me contenter de mettre à jour mon propre dépot sur ce point là sans remonter la modification)
4. Gérer la rétrocompatibilité autrement (en fonction de la date du contrat par exemple).

**Quelle solution te semble la plus adaptée ?**

**Comment by bsongis** [comment]
Il ne me semble pas envisageable, en effet, d'imposer cette troncature à l'ensemble des utilisateurs. (Aucune base légale pour ce mode d'arrondi, interprétations variables suivant les lieux et les inspections CAF...l'arrondi le plus proche reste l'arrondi le plus juste).
Aussi j'aimerais privilégier l'option 3, quitte à envisager par la suite, si une demande émerge, une option de configuration.

**Comment by mistraloz** [comment]
Je fais comme ça dans ce cas. Cependant, même si la consigne de la CNAF n'est pas claire, sur le site mon-enfant.fr (édité par la CNAF), aucune ambiguité, il s'agit d'une troncature.
