### ISSUE TITLE
Dépendances du paquet Linux

### ISSUE THREAD

**Issue by koocotte** [studio1247/gertrude#19]
Le paquet n'indique pas toutes les dépendances nécessaires (selon les distributions).

Sur Ubuntu 10.4 LTS, l'installation n'est pas possible car dpkg-deb 1.15.5 ne prends pas en charge la compression xz. Sur une 14.04, cela fonctionne avec dpkg-deb 1.17.5

Sur Ubuntu 14.04 LTS, il est nécessaire d'installer python-wxgtk2.8

**Comment by bsongis** [comment]
What says dpkg -I ? The dependency should be there

**Comment by bsongis** [comment]
Que dit dpkg -I <package>
La dépendance devrait y être

**Comment by bsongis** [comment]
J'ai mis en ligne une version 1.00c

**Comment by koocotte** [comment]
J'ai `Depends: bash, python-gtk2, python`

**Comment by bsongis** [comment]
Donc la dépendance y est bien, non ?

**Comment by koocotte** [comment]
J'ai bien une dépendance sur python-gtk2, mais pas sur python-wxgtk2.8; et l'installation du premier n'entraine pas le second.
```
% apt-cache show python-gtk2 | grep Depends
Depends: python (>= 2.7), python (<< 2.8), python:any (>= 2.7.1-0ubuntu2), libatk1.0-0 (>= 1.12.4), libc6 (>= 2.14), libcairo2 (>= 1.2.4), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.24.0), libgtk2.0-0 (>= 2.24.0), libpango-1.0-0 (>= 1.22.0), libpangocairo-1.0-0 (>= 1.21.4), python-cairo (>= 1.0.2-1.1), python-gobject-2 (>= 2.21.3)
```

**Comment by koocotte** [comment]
Merci !
