### ISSUE TITLE
Période d'adaptation => le planning n'en tient pas compte

### ISSUE THREAD

**Issue by mistraloz** [studio1247/gertrude#20]
Bonjour Bertrand,

Il m'avait semblé que lorsque la période d'adaptation n'était pas indiquée (ou si elle était indiquée dans le future), l'enfant apparaissait sur le planing mais sans réservation d'horaire (charge à la crèche d'indiquer les horaires de présence en adaptation). 

Je viens de tester et cela ne semble pas le cas. Est-ce que cela a changé ? (ou est-ce juste moi qui ait mal compris ?)

**Comment by bsongis** [comment]
Non ça n'a jamais été fait !

**Comment by mistraloz** [comment]
Merci pour la réponse rapide ! Nous allons nous arranger autrement pour le moment (je clos le ticket et ferai un mail si nous souhaitons envisager une évolution).
