### ISSUE TITLE
Problème affichage planning

### ISSUE THREAD

**Issue by pdgaaa** [studio1247/gertrude#23]
![2016-01-25-1453760253_1366x768](https://cloud.githubusercontent.com/assets/10196231/12566530/6a9a2a3e-c3ba-11e5-83bf-fe9d33e54e6b.png)

Sous Ubuntu 15.10. Testé également sur une mint 17.

Pas de problème avec la version 1.01l, mais depuis le passage en 1.04h et test avec 1.04l, l'affichage du planning ne fonctionne plus.

Merci.

**Comment by bsongis** [comment]
Vous pouvez m'envoyer votre base de données par mail ? Je n'ai pas de problème sur Debian avec les données de test.

**Comment by bsongis** [comment]
Pas de problème sur Debian avec vos données

**Comment by pdgaaa** [comment]
Ok, mais ça ne m'avance pas beaucoup.

Serait-ce un problème python ? comment puis-je débugger pour avancer ?

Le 26 janvier 2016 à 23:18, Bertrand Songis <notifications@github.com> a
écrit :

**Comment by pdgaaa** [comment]
Je viens de tester version après version et le problème apparaît à la version 1.03b (1.02g fonctionnelle), après la refonte du planning du 24/11/2015.

**Comment by pdgaaa** [comment]
Ok, corrigé à la version 1.04o. https://github.com/studio1247/gertrude/commit/4180417ad6339f24cfe91daba8c0c308e84a6584
Bug gtk. La version sous ubuntu 15.10 est python-wxgtk2.8 (2.8.12.1+dfsg2-2ubuntu2)
