### ISSUE TITLE
Gestion des branches à améliorer

### ISSUE THREAD

**Issue by stevebeauge** [studio1247/gertrude#24]
Bonjour, et tout d'abords merci pour le choix de l'open source.

Toutefois, je constate que tous les commits se font directement dans la branche master.
La branche release semble inactive.

Il est alors difficile de savoir ce qui est considéré comme stable et ce qui est du "work in progress".

Si on pousse le raisonnement à l'extreme, je vous suggérerait de suivre le modèle [gitflow](http://nvie.com/posts/a-successful-git-branching-model/).

Il ouvrirait aussi plus facilement la voie aux contributions.

**Comment by bsongis** [comment]
Oui pour la théorie, mais tant qu'il n'y a pas plus de contributeurs, il n'est pas nécessaire de s'encombrer avec des process plus compliqués.
