### ISSUE TITLE
Bitdefender considère gertrude comme un malware

### ISSUE THREAD

**Issue by stevebeauge** [studio1247/gertrude#25]
Bonjour,

L'antivirus Bitdefender bloque le téléchargement de gertrude, qualifié de malware.
Il est d'ailleurs noté comme tel sur [virustotal](https://www.virustotal.com/fr/url/2138ee437ed6da91d705adcb16d768b32c5952a49bce59a31116ed1d6ca04b82/analysis/1461253678/)

Faux positif?

**Comment by bsongis** [comment]
Oui bon ... à vous de voir, vous avez une culture suffisante pour vous faire une idée du programme :)

**Comment by stevebeauge** [comment]
Moi, oui, mais pour des utilisateurs de base ça bloque toute mise à jour possible du logiciel, sans passer par une autre machine.
