### ISSUE TITLE
Relevé salariés et période de congés

### ISSUE THREAD

**Issue by pdgaaa** [studio1247/gertrude#26]
Bonjour,

Les périodes de congés n'apparaissent pas dans le relevé mensuel des salariés du Tableau de bord. Ni celles définies dans les paramètres de configuration ni celles directement mises au niveau des salariés.
Est-ce normal ? 

De plus dans le relevé sous libreoffice, la colonne Total reste à 0. Pourtant la formule est bonne. Si je l'efface et que je refais l'adition, ça marche.

Merci.
(Gertrude 1.08b)

**Comment by bsongis** [comment]
Il faut changer les paramètres LibreOffice pour lui demander de recalculer les formules au chargement d'un document
