### ISSUE TITLE
V1.12.12 no such column: email

### ISSUE THREAD

**Issue by Francoislaba** [studio1247/gertrude#30]
Bonjour,

Je teste actuellement Gertrude (beau travail). Samedi j'ai téléchargé la version 1.12.10 sans problème particulier.

Aujourd'hui j'éssai avec la nouvelle version 1.12.12 avec une nouvelle base vierge et impossible d'ajouter une inscription et à la réouverture de la base, la base ne s'ouvre pas avec comme message:

Chargement en mémoire de la base ...
no such column: email
Erreur lors du chargement !

Merci,

François

**Comment by bsongis** [comment]
Oui effectivement, merci de m'avoir prévenu

**Comment by bsongis** [comment]
Corrigé en version 1.12.13
