### ISSUE TITLE
Copie de secours des données

### ISSUE THREAD

**Issue by Francoislaba** [studio1247/gertrude#31]
Bonjour,

La fonction du menu déroulant "Fichier", "Copie de secours des données" ne semble pas fonctionner.

J'ai bien la boite de dialogue "Select a file" avec un le nom de fichier proposé par défaut "gertrude-11-9-2017.zip", mais le fichier ne se créé pas et ne s'enregistre pas dans le répertoire de destination.

Config: V1.12.14 - Windows 10 64bits

**Comment by bsongis** [comment]
Corrigé en 1.12.15

**Comment by Francoislaba** [comment]
Merci pour votre réactivité!
