### ISSUE TITLE
Plannings et sélection des plages horaires

### ISSUE THREAD

**Issue by Francoislaba** [studio1247/gertrude#32]
Bonjour,

Sur l'ensemble plannings et dans le cadre de la sélection des plages horaires:

1. Cliquer une première fois pour déterminer le début de la plage horaire
2. Glisser la souris sur la ligne suivante sans relâcher le bouton de la souris  pour déterminer une plage horaire sur un autre jour
-> En essayant de sortir du tableau pour faire autre chose, le planning se modifie au déplacement de la souris.

Cela se produit également si l'on relâche le bouton de la souris en dehors des limites du tableau.

Ne serait-il pas possible de considérer que lorsque le bouton de la souris n'est pas relâcher et que le pointeur se trouve sur une autre ligne ou en dehors des limites du tableau, que la sélection de la plage horaire est validée?

**Comment by bsongis** [comment]
Prévoir une adaptation pour ce genre de modification du logiciel
