### ISSUE TITLE
Molette de la souris / Scrollbar et menus déroulants

### ISSUE THREAD

**Issue by Francoislaba** [studio1247/gertrude#34]
Bonjour,

Lorsque l'on utilise la molette de la souris dans les parties du logiciel où une Scrollbar est présente et que la souris est positionnée sur une liste de choix déroulante, c'est le déroulement de la liste qui est prioritaire et non la Scollbar.

je rencontre souvent des difficultés sur la "fiche des parents et référents", lorsqu'on souhaite utiliser la Scrollbar à la souris pour afficher les informations suivantes et que le pointeur est positionné sur la "relation" ou sur "les revenus"...

N'est-il pas possible de désactiver l'action de la molette de la souris sur les listes déroulantes pour rendre prioritaire la Scrollbar à la molette et ainsi éviter des modifications involontaires?

**Comment by Francoislaba** [comment]
Info complémentaire:

Dans inscriptions -> Parents et référents ,
Lorsque par erreur la molette de la souris est utilisée sur la liste "Relation" et que l'on va jusqu'à "Parent manquant", toutes les informations saisies précédemment pour la mère ou le père ne sont pas conservées.

**Comment by bsongis** [comment]
En fait c'est le comportement par défaut de Windows et j'en conviens c'est très pénible.
Je crois qu'il faut intercepter l'évènement MOUSE_WHEEL et ne rien faire lorsque le widget n'a pas le focus
Je vais essayer quand j'aurai une minute

**Comment by ameurenand** [comment]
La correction fonctionne mais par contre on ne peut plus utiliser la molette de la souris pour scroller dans cet onglet. N'est-il pas possible de transférer l'événement MOUSE_WHEEL au panel parent?
