### ISSUE TITLE
Problème avec les arrondis de la mensualisation des heures

### ISSUE THREAD

**Issue by Francoislaba** [studio1247/gertrude#35]
V1.12.15

Bonjour,

J'ai deux problèmes qui semblent être liés:

1. Dans inscriptions -> Mode d'accueil,  avec le mode "pas d'arrondi" pour la mensualisation des heures
 ****Lorsqu'on modifie les plages horaires du planning de référence, le nombre d'heures de gardes mensuelles ne bouge pas dans la section "Frais de garde".

2. Si l'on enregistre la base avec le mode "pas d'arrondi" pour la mensualisation des heures, que l'on ferme Gertrude et qu'on le ré-ouvre, le mode n'est pas conservé et revient sur "Arrondi à l'heure la plus proche.

3. Avec une période d'inscription sur un an; avec 227 jours de présence,  10 heures par jour et avec mensualisation sur la période de contrat on devrait avoir (227*10)/12 = 189,17 heures pour le nombre d'heures de gardes mensuelles.
Seulement, Gertrude affiche 190.0 heures avec le mode "sans arrondi". Même résultat avec le mode "heure la plus proche."
Sans arrondi ne devrait-on pas avoir 189,2h et sur l'heure la plus proche 189?

**Comment by bsongis** [comment]
Prendre un forfait maintenance / garantie pour qu'on vous explique les différents modes d'arrondi et la gestion des périodes

**Comment by Francoislaba** [comment]
**Avec la même base, en version 1.12.10, aucun souci** avec les arrondis. La même base ouverte , dans la version 1.12.15, plus de gestion d'arrondis

**Si l'on enregistre la base avec le mode "pas d'arrondi" pour la mensualisation des heures, que l'on ferme Gertrude et qu'on le ré-ouvre, le mode n'est pas conservé et revient sur "Arrondi à l'heure la plus proche".**

Paramètres:
- PSU
- Avec mensualisation sur la période du contrat
- Déduction en jours précis
