### ISSUE TITLE
Nouvelle fonctionnalité : règle des 115%

### ISSUE THREAD

**Issue by nathonline** [studio1247/gertrude#42]
Sur la fiche structure on peut indiquer le nombre d'enfants que l'on peut accueillir.
Cependant la legislation nous autorise à faire des gardes à environ 115%de l'effectif autorisé à condition que le volume horaire hebdomadaire de garde d'enfant reste à 100%.  (creche de 10 enfants alors 12 enfants possibles, crèche de 12 enfants alors 14 enfants possibles) 

A titre d'exemple : le lundi de 8h à 10h il est accueilli que 10 enfants pour un agrément de 12. l'apres midi il est alors possible d'accueillir 14 enfants de 14h à 16h par exemple.

La condition 1 : on ne depasse pas le quota de 100% sur la semaine est respectée
La condition 2 : 14 enfants pour un agrément de 12 est respectée

Il serait intéressant qu'un indicateur graphique permette d'indiquer si une de ces 2 conditions ne sont pas respectées

**Comment by bsongis** [comment]
Oui, mais sur la version en ligne, pas celle-là qui date trop, je ne suis pas certain que beaucoup de structures l'utilisent encore et que je ne ferai pas un développement pareil pour rien !
