### ISSUE TITLE
Nouvelle fonctionnalité : Planning pro hors garde d'enfants

### ISSUE THREAD

**Issue by nathonline** [studio1247/gertrude#43]
Une réferente technique est détachée minimum 7 heures par semaine afin de s'occuper de tâches administratives.
Il serait intéressant de pouvoir séparer ces heures de travail de la garde d'enfant par une couleur différente et un libellé.

Cela peut etre aussi utile pour marquer des réunions d'équipe

**Comment by nathonline** [comment]
Fonctionnalité existante

**Comment by bsongis** [comment]
Disponible uniquement dans la version en ligne de Gertrude

**Comment by bsongis** [comment]
Les réunions d'équipe sont également disponibles dans la section "Agenda" avec report sur le planning
