### ISSUE TITLE
Incohérence entre statistiques et planning

### ISSUE THREAD

**Issue by blaiseli** [studio1247/gertrude#44]
Bonjour,

Dans la version en ligne de Gertrude, j'observe une incohérence entre les données entrées dans le planning et celles affichées dans les statistiques du tableau de bord, au moins dans le cas suivant:

Pour le mois de septembre, les statistiques indiquent autant d'heures facturées que d'heures réalisées:
![frequentation_2022_Gertrude](https://user-images.githubusercontent.com/3380503/222881646-31216e1b-f502-43c3-90c9-d3fccfb367d0.png)

Les données chiffrées figurant dans le tableau plus bas sur la page, ainsi que celles téléchargeables sour forme de fichier .ods indiquent également le même nombre d'heures facturées et réalisées, y compris au niveau des individus (pour le fichier .ods)).

Pourtant, les données entrées dans le planning pour ce mois-ci semblent "normales", par exemple, pour le 26 septembre:
![planning_26_septembre_2022_Gertrude](https://user-images.githubusercontent.com/3380503/222881371-8cabb933-eb05-453d-8c70-ef72084247fd.png)

N'étant pas en charge des factures et du planning, je précise que je n'ai pas accès en tant qu'administrateur, uniquement comme "observateur", mais les parents ayant un accès plus étendu observent également ce problème.

**Comment by bsongis** [comment]
Les chiffres actuellement saisis au planning ont été modifiés après clôture de factures. Les statistiques sont générées à partir des factures clôturées et non recalculées en permanence sur la base des plannings.

Je viens de pointer intégralement vos données de septembre 2022 après déclôture de toutes les factures (sur un espace de test) et les statistiques correspondent bien exactement à votre saisie.

PS : ceci est le repo pour la version sur poste de Gertrude, pas la version en ligne !

**Comment by blaiseli** [comment]
Merci pour votre réponse.
Je pensais que la même base de code servait pour la version en ligne et la version à installer en local.
Où se trouve le dépôt correspondant à la version en ligne ?

**Comment by bsongis** [comment]
Elle n'est pas sous license GPL, pour des raisons évidentes !
